/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siscom.view;

import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author cesar
 */
public class ContaBancariaView extends JPanel {

    public ContaBancariaView() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("siscomPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT b FROM ContaBancaria b");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        pnlDadosConta = new javax.swing.JPanel();
        lblContaCodigoBanco = new javax.swing.JLabel();
        lblContaAgencia = new javax.swing.JLabel();
        lblContaNumero = new javax.swing.JLabel();
        lblContaGerenteBanco = new javax.swing.JLabel();
        lblContaTelefoneBanco = new javax.swing.JLabel();
        txtContaCodigoBanco = new javax.swing.JTextField();
        txtContaAgencia = new javax.swing.JTextField();
        txtContaNumero = new javax.swing.JTextField();
        txtContaGerenteBanco = new javax.swing.JTextField();
        txtContaTelefoneBanco = new javax.swing.JTextField();
        pnlListaContas = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        tblContas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnNovaConta = new javax.swing.JButton();
        btnExluirConta = new javax.swing.JButton();
        btnCancelarConta = new javax.swing.JButton();
        btnConfirmarConta = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        pnlDadosConta.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Conta"));

        lblContaCodigoBanco.setText("Código do Banco:");

        lblContaAgencia.setText("Número da Agência:");

        lblContaNumero.setText("Número da Conta:");

        lblContaGerenteBanco.setText("Gerente do Banco:");

        lblContaTelefoneBanco.setText("Telefone do Banco:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigoBanco}"), txtContaCodigoBanco, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtContaCodigoBanco, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numeroAgencia}"), txtContaAgencia, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtContaAgencia, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.numeroConta}"), txtContaNumero, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtContaNumero, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nomeGerente}"), txtContaGerenteBanco, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtContaGerenteBanco, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.foneBanco}"), txtContaTelefoneBanco, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtContaTelefoneBanco, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnlDadosContaLayout = new javax.swing.GroupLayout(pnlDadosConta);
        pnlDadosConta.setLayout(pnlDadosContaLayout);
        pnlDadosContaLayout.setHorizontalGroup(
            pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContaCodigoBanco)
                    .addComponent(lblContaAgencia)
                    .addComponent(lblContaNumero)
                    .addComponent(lblContaGerenteBanco)
                    .addComponent(lblContaTelefoneBanco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContaCodigoBanco)
                    .addComponent(txtContaAgencia)
                    .addComponent(txtContaNumero)
                    .addComponent(txtContaGerenteBanco)
                    .addComponent(txtContaTelefoneBanco))
                .addContainerGap())
        );
        pnlDadosContaLayout.setVerticalGroup(
            pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContaCodigoBanco)
                    .addComponent(txtContaCodigoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContaAgencia)
                    .addComponent(txtContaAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContaNumero)
                    .addComponent(txtContaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContaGerenteBanco)
                    .addComponent(txtContaGerenteBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContaTelefoneBanco)
                    .addComponent(txtContaTelefoneBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlListaContas.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Contas Bancárias"));

        tblContas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblContas.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tblContas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoBanco}"));
        columnBinding.setColumnName("Código do Banco");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroAgencia}"));
        columnBinding.setColumnName("Número da Agência");
        columnBinding.setColumnClass(Short.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${numeroConta}"));
        columnBinding.setColumnName("Número da Conta");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomeGerente}"));
        columnBinding.setColumnName("Gerente do Banco");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${foneBanco}"));
        columnBinding.setColumnName("Telefone do Banco");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(tblContas);
        if (tblContas.getColumnModel().getColumnCount() > 0) {
            tblContas.getColumnModel().getColumn(0).setResizable(false);
            tblContas.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblContas.getColumnModel().getColumn(1).setResizable(false);
            tblContas.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblContas.getColumnModel().getColumn(2).setResizable(false);
            tblContas.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblContas.getColumnModel().getColumn(3).setMinWidth(250);
            tblContas.getColumnModel().getColumn(4).setResizable(false);
            tblContas.getColumnModel().getColumn(4).setPreferredWidth(120);
        }

        javax.swing.GroupLayout pnlListaContasLayout = new javax.swing.GroupLayout(pnlListaContas);
        pnlListaContas.setLayout(pnlListaContasLayout);
        pnlListaContasLayout.setHorizontalGroup(
            pnlListaContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaContasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlListaContasLayout.setVerticalGroup(
            pnlListaContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(masterScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        btnNovaConta.setText("Nova");
        btnNovaConta.setToolTipText("");
        btnNovaConta.addActionListener(formListener);

        btnExluirConta.setText("Excluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblContas, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnExluirConta, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnExluirConta.addActionListener(formListener);

        btnCancelarConta.setText("Cancelar Allterações");
        btnCancelarConta.addActionListener(formListener);

        btnConfirmarConta.setText("Confirmar Allterações");
        btnConfirmarConta.addActionListener(formListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovaConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExluirConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarConta)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarConta, btnConfirmarConta, btnExluirConta, btnNovaConta});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarConta)
                    .addComponent(btnCancelarConta)
                    .addComponent(btnExluirConta)
                    .addComponent(btnNovaConta))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlListaContas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListaContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == btnNovaConta) {
                ContaBancariaView.this.btnNovaContaActionPerformed(evt);
            }
            else if (evt.getSource() == btnExluirConta) {
                ContaBancariaView.this.btnExluirContaActionPerformed(evt);
            }
            else if (evt.getSource() == btnCancelarConta) {
                ContaBancariaView.this.btnCancelarContaActionPerformed(evt);
            }
            else if (evt.getSource() == btnConfirmarConta) {
                ContaBancariaView.this.btnConfirmarContaActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void btnCancelarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarContaActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_btnCancelarContaActionPerformed

    private void btnExluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExluirContaActionPerformed
        int[] selected = tblContas.getSelectedRows();
        List<br.com.siscom.bean.ContaBancaria> toRemove = new ArrayList<>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            br.com.siscom.bean.ContaBancaria b = list.get(tblContas.convertRowIndexToModel(selected[idx]));
            toRemove.add(b);
            entityManager.remove(b);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_btnExluirContaActionPerformed

    private void btnNovaContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaContaActionPerformed
        br.com.siscom.bean.ContaBancaria b = new br.com.siscom.bean.ContaBancaria();
        entityManager.persist(b);
        list.add(b);
        int row = list.size() - 1;
        tblContas.setRowSelectionInterval(row, row);
        tblContas.scrollRectToVisible(tblContas.getCellRect(row, 0, true));
    }//GEN-LAST:event_btnNovaContaActionPerformed

    private void btnConfirmarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarContaActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            entityManager.getTransaction().begin();
            List<br.com.siscom.bean.ContaBancaria> merged = new ArrayList<>(list.size());
            for (br.com.siscom.bean.ContaBancaria b : list) {
                merged.add(entityManager.merge(b));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_btnConfirmarContaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarConta;
    private javax.swing.JButton btnConfirmarConta;
    private javax.swing.JButton btnExluirConta;
    private javax.swing.JButton btnNovaConta;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContaAgencia;
    private javax.swing.JLabel lblContaCodigoBanco;
    private javax.swing.JLabel lblContaGerenteBanco;
    private javax.swing.JLabel lblContaNumero;
    private javax.swing.JLabel lblContaTelefoneBanco;
    private java.util.List<br.com.siscom.bean.ContaBancaria> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JPanel pnlDadosConta;
    private javax.swing.JPanel pnlListaContas;
    private javax.persistence.Query query;
    private javax.swing.JTable tblContas;
    private javax.swing.JTextField txtContaAgencia;
    private javax.swing.JTextField txtContaCodigoBanco;
    private javax.swing.JTextField txtContaGerenteBanco;
    private javax.swing.JTextField txtContaNumero;
    private javax.swing.JTextField txtContaTelefoneBanco;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(final String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContaBancariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new ContaBancariaView());
                //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                if (args.length > 0) {
                    frame.setTitle(args[0]);
                }
            }
        });
    }

}
