/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siscom.view;

import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author cesar
 */
public class FornecedorView extends JPanel {

    public FornecedorView() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("siscomPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT f FROM Fornecedor f");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        pnlListaFornecedores = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        pnlDadosFornecedor = new javax.swing.JPanel();
        lblFornecedorNome = new javax.swing.JLabel();
        lblFornecedorCPF = new javax.swing.JLabel();
        lblFornecedorRG = new javax.swing.JLabel();
        lblFornecedorOrgaoExpedidor = new javax.swing.JLabel();
        lblFornecedorCNPJ = new javax.swing.JLabel();
        lblFornecedorTipo = new javax.swing.JLabel();
        lblFornecedorLogradouro = new javax.swing.JLabel();
        lblFornecedorBairro = new javax.swing.JLabel();
        lblFornecedorCidade = new javax.swing.JLabel();
        lblFornecedorUF = new javax.swing.JLabel();
        lblFornecedorCEP = new javax.swing.JLabel();
        lblFornecedorEmail = new javax.swing.JLabel();
        lblFornecedorSite = new javax.swing.JLabel();
        lblFornecedorTelefone = new javax.swing.JLabel();
        lblFornecedorCelular = new javax.swing.JLabel();
        lblFornecedorFax = new javax.swing.JLabel();
        lblFornecedorContato = new javax.swing.JLabel();
        txtFornecedorNome = new javax.swing.JTextField();
        txtFornecedorRG = new javax.swing.JTextField();
        txtFornecedorOrgaoExpedidor = new javax.swing.JTextField();
        txtFornecedorCNPJ = new javax.swing.JTextField();
        txtFornecedorTipo = new javax.swing.JTextField();
        txtFornecedorLogradouro = new javax.swing.JTextField();
        txtFornecedorBairro = new javax.swing.JTextField();
        txtFornecedorCidade = new javax.swing.JTextField();
        txtFornecedorUF = new javax.swing.JTextField();
        txtFornecedorCEP = new javax.swing.JTextField();
        txtFornecedorEmail = new javax.swing.JTextField();
        txtFornecedorSite = new javax.swing.JTextField();
        txtFornecedorTelefone = new javax.swing.JTextField();
        txtFornecedorCelular = new javax.swing.JTextField();
        txtFornecedorFax = new javax.swing.JTextField();
        txtFornecedorContato = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        btnConfirmarFornecedor = new javax.swing.JButton();
        btnCancelarFornecedor = new javax.swing.JButton();
        btnNovoFornecedor = new javax.swing.JButton();
        btnExcluirFornecedor = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        pnlListaFornecedores.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Fornecedores"));

        tblFornecedores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblFornecedores.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tblFornecedores);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Fornecedor");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipo}"));
        columnBinding.setColumnName("Tipo");
        columnBinding.setColumnClass(Character.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("E-mail");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cnpj}"));
        columnBinding.setColumnName("CNPJ");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpf}"));
        columnBinding.setColumnName("CPF");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rg}"));
        columnBinding.setColumnName("RG");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${orgaoRg}"));
        columnBinding.setColumnName("Órgão expedidor");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefone}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${celular}"));
        columnBinding.setColumnName("Celular");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fax}"));
        columnBinding.setColumnName("Fax");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${logradouro}"));
        columnBinding.setColumnName("Logradouro");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bairro}"));
        columnBinding.setColumnName("Bairro");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cep}"));
        columnBinding.setColumnName("CEP");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cidade}"));
        columnBinding.setColumnName("Cidade");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${uf}"));
        columnBinding.setColumnName("UF");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${contato}"));
        columnBinding.setColumnName("Contato");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${site}"));
        columnBinding.setColumnName("Site");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(tblFornecedores);
        if (tblFornecedores.getColumnModel().getColumnCount() > 0) {
            tblFornecedores.getColumnModel().getColumn(0).setMinWidth(200);
            tblFornecedores.getColumnModel().getColumn(1).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblFornecedores.getColumnModel().getColumn(2).setMinWidth(150);
            tblFornecedores.getColumnModel().getColumn(3).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblFornecedores.getColumnModel().getColumn(4).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(4).setPreferredWidth(80);
            tblFornecedores.getColumnModel().getColumn(5).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(5).setPreferredWidth(80);
            tblFornecedores.getColumnModel().getColumn(6).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(6).setPreferredWidth(130);
            tblFornecedores.getColumnModel().getColumn(7).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblFornecedores.getColumnModel().getColumn(8).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(8).setPreferredWidth(100);
            tblFornecedores.getColumnModel().getColumn(9).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(9).setPreferredWidth(100);
            tblFornecedores.getColumnModel().getColumn(10).setMinWidth(250);
            tblFornecedores.getColumnModel().getColumn(11).setMinWidth(150);
            tblFornecedores.getColumnModel().getColumn(12).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(12).setPreferredWidth(80);
            tblFornecedores.getColumnModel().getColumn(13).setMinWidth(150);
            tblFornecedores.getColumnModel().getColumn(14).setResizable(false);
            tblFornecedores.getColumnModel().getColumn(14).setPreferredWidth(50);
            tblFornecedores.getColumnModel().getColumn(15).setMinWidth(200);
            tblFornecedores.getColumnModel().getColumn(16).setMinWidth(200);
        }

        javax.swing.GroupLayout pnlListaFornecedoresLayout = new javax.swing.GroupLayout(pnlListaFornecedores);
        pnlListaFornecedores.setLayout(pnlListaFornecedoresLayout);
        pnlListaFornecedoresLayout.setHorizontalGroup(
            pnlListaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane)
                .addContainerGap())
        );
        pnlListaFornecedoresLayout.setVerticalGroup(
            pnlListaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlDadosFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Fornecedor"));

        lblFornecedorNome.setText("Nome:");

        lblFornecedorCPF.setText("CPF:");

        lblFornecedorRG.setText("RG:");

        lblFornecedorOrgaoExpedidor.setText("Órgão expedidor:");

        lblFornecedorCNPJ.setText("CNPJ:");

        lblFornecedorTipo.setText("Tipo:");

        lblFornecedorLogradouro.setText("Logradouro:");

        lblFornecedorBairro.setText("Bairro:");

        lblFornecedorCidade.setText("Cidade:");

        lblFornecedorUF.setText("UF:");

        lblFornecedorCEP.setText("CEP:");

        lblFornecedorEmail.setText("E-mail:");

        lblFornecedorSite.setText("Site:");

        lblFornecedorTelefone.setText("Telefone:");

        lblFornecedorCelular.setText("Celular:");

        lblFornecedorFax.setText("Fax:");

        lblFornecedorContato.setText("Contato:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), txtFornecedorNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorNome, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.rg}"), txtFornecedorRG, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorRG, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.orgaoRg}"), txtFornecedorOrgaoExpedidor, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorOrgaoExpedidor, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cnpj}"), txtFornecedorCNPJ, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorCNPJ, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tipo}"), txtFornecedorTipo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorTipo, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.logradouro}"), txtFornecedorLogradouro, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorLogradouro, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.bairro}"), txtFornecedorBairro, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorBairro, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cidade}"), txtFornecedorCidade, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorCidade, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.uf}"), txtFornecedorUF, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorUF, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cep}"), txtFornecedorCEP, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorCEP, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.email}"), txtFornecedorEmail, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorEmail, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.site}"), txtFornecedorSite, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorSite, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.telefone}"), txtFornecedorTelefone, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorTelefone, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.celular}"), txtFornecedorCelular, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorCelular, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.fax}"), txtFornecedorFax, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorFax, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.contato}"), txtFornecedorContato, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtFornecedorContato, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.cpf}"), jFormattedTextField1, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), jFormattedTextField1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnlDadosFornecedorLayout = new javax.swing.GroupLayout(pnlDadosFornecedor);
        pnlDadosFornecedor.setLayout(pnlDadosFornecedorLayout);
        pnlDadosFornecedorLayout.setHorizontalGroup(
            pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFornecedorContato, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorFax, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorCelular, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorTelefone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorSite, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorCEP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorUF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorCidade, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorBairro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorLogradouro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorCNPJ, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorCPF, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFornecedorNome, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFornecedorNome)
                    .addComponent(txtFornecedorLogradouro)
                    .addComponent(txtFornecedorBairro)
                    .addComponent(txtFornecedorCidade)
                    .addComponent(txtFornecedorUF)
                    .addComponent(txtFornecedorCEP)
                    .addComponent(txtFornecedorEmail)
                    .addComponent(txtFornecedorSite)
                    .addComponent(txtFornecedorTelefone)
                    .addComponent(txtFornecedorCelular)
                    .addComponent(txtFornecedorFax)
                    .addComponent(txtFornecedorContato)
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFornecedorTipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFornecedorCNPJ, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFornecedorRG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFornecedorRG, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFornecedorOrgaoExpedidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFornecedorOrgaoExpedidor)))
                .addContainerGap())
        );
        pnlDadosFornecedorLayout.setVerticalGroup(
            pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorNome)
                    .addComponent(txtFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorCPF)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFornecedorRG)
                    .addComponent(txtFornecedorRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFornecedorOrgaoExpedidor)
                    .addComponent(txtFornecedorOrgaoExpedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorCNPJ)
                    .addComponent(txtFornecedorCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorTipo)
                    .addComponent(txtFornecedorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorLogradouro)
                    .addComponent(txtFornecedorLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorBairro)
                    .addComponent(txtFornecedorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorCidade)
                    .addComponent(txtFornecedorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorUF)
                    .addComponent(txtFornecedorUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorCEP)
                    .addComponent(txtFornecedorCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorEmail)
                    .addComponent(txtFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorSite)
                    .addComponent(txtFornecedorSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorTelefone)
                    .addComponent(txtFornecedorTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorCelular)
                    .addComponent(txtFornecedorCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorFax)
                    .addComponent(txtFornecedorFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFornecedorContato)
                    .addComponent(txtFornecedorContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnConfirmarFornecedor.setText("Confirmar Allterações");
        btnConfirmarFornecedor.addActionListener(formListener);

        btnCancelarFornecedor.setText("Cancelar Allterações");
        btnCancelarFornecedor.addActionListener(formListener);

        btnNovoFornecedor.setText("Novo");
        btnNovoFornecedor.addActionListener(formListener);

        btnExcluirFornecedor.setText("Excluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblFornecedores, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnExcluirFornecedor, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnExcluirFornecedor.addActionListener(formListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarFornecedor)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarFornecedor, btnConfirmarFornecedor, btnExcluirFornecedor, btnNovoFornecedor});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarFornecedor)
                    .addComponent(btnCancelarFornecedor)
                    .addComponent(btnExcluirFornecedor)
                    .addComponent(btnNovoFornecedor))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlListaFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == btnConfirmarFornecedor) {
                FornecedorView.this.btnConfirmarFornecedorActionPerformed(evt);
            }
            else if (evt.getSource() == btnCancelarFornecedor) {
                FornecedorView.this.btnCancelarFornecedorActionPerformed(evt);
            }
            else if (evt.getSource() == btnNovoFornecedor) {
                FornecedorView.this.btnNovoFornecedorActionPerformed(evt);
            }
            else if (evt.getSource() == btnExcluirFornecedor) {
                FornecedorView.this.btnExcluirFornecedorActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void btnCancelarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFornecedorActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_btnCancelarFornecedorActionPerformed

    private void btnExcluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFornecedorActionPerformed
        int[] selected = tblFornecedores.getSelectedRows();
        List<br.com.siscom.bean.Fornecedor> toRemove = new ArrayList<>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            br.com.siscom.bean.Fornecedor f = list.get(tblFornecedores.convertRowIndexToModel(selected[idx]));
            toRemove.add(f);
            entityManager.remove(f);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_btnExcluirFornecedorActionPerformed

    private void btnNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoFornecedorActionPerformed
        br.com.siscom.bean.Fornecedor f = new br.com.siscom.bean.Fornecedor();
        entityManager.persist(f);
        list.add(f);
        int row = list.size() - 1;
        tblFornecedores.setRowSelectionInterval(row, row);
        tblFornecedores.scrollRectToVisible(tblFornecedores.getCellRect(row, 0, true));
    }//GEN-LAST:event_btnNovoFornecedorActionPerformed

    private void btnConfirmarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarFornecedorActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            entityManager.getTransaction().begin();
            List<br.com.siscom.bean.Fornecedor> merged = new ArrayList<>(list.size());
            for (br.com.siscom.bean.Fornecedor f : list) {
                merged.add(entityManager.merge(f));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_btnConfirmarFornecedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarFornecedor;
    private javax.swing.JButton btnConfirmarFornecedor;
    private javax.swing.JButton btnExcluirFornecedor;
    private javax.swing.JButton btnNovoFornecedor;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFornecedorBairro;
    private javax.swing.JLabel lblFornecedorCEP;
    private javax.swing.JLabel lblFornecedorCNPJ;
    private javax.swing.JLabel lblFornecedorCPF;
    private javax.swing.JLabel lblFornecedorCelular;
    private javax.swing.JLabel lblFornecedorCidade;
    private javax.swing.JLabel lblFornecedorContato;
    private javax.swing.JLabel lblFornecedorEmail;
    private javax.swing.JLabel lblFornecedorFax;
    private javax.swing.JLabel lblFornecedorLogradouro;
    private javax.swing.JLabel lblFornecedorNome;
    private javax.swing.JLabel lblFornecedorOrgaoExpedidor;
    private javax.swing.JLabel lblFornecedorRG;
    private javax.swing.JLabel lblFornecedorSite;
    private javax.swing.JLabel lblFornecedorTelefone;
    private javax.swing.JLabel lblFornecedorTipo;
    private javax.swing.JLabel lblFornecedorUF;
    private java.util.List<br.com.siscom.bean.Fornecedor> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JPanel pnlDadosFornecedor;
    private javax.swing.JPanel pnlListaFornecedores;
    private javax.persistence.Query query;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtFornecedorBairro;
    private javax.swing.JTextField txtFornecedorCEP;
    private javax.swing.JTextField txtFornecedorCNPJ;
    private javax.swing.JTextField txtFornecedorCelular;
    private javax.swing.JTextField txtFornecedorCidade;
    private javax.swing.JTextField txtFornecedorContato;
    private javax.swing.JTextField txtFornecedorEmail;
    private javax.swing.JTextField txtFornecedorFax;
    private javax.swing.JTextField txtFornecedorLogradouro;
    private javax.swing.JTextField txtFornecedorNome;
    private javax.swing.JTextField txtFornecedorOrgaoExpedidor;
    private javax.swing.JTextField txtFornecedorRG;
    private javax.swing.JTextField txtFornecedorSite;
    private javax.swing.JTextField txtFornecedorTelefone;
    private javax.swing.JTextField txtFornecedorTipo;
    private javax.swing.JTextField txtFornecedorUF;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(final String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new FornecedorView());
                //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                if (args.length > 0) {
                    frame.setTitle(args[0]);
                }
            }
        });
    }

}
