/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siscom.view;

/**
 *
 * @author cesar
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnCadastroCliente = new javax.swing.JButton();
        btnCadastroFornecedor = new javax.swing.JButton();
        btnCadastroProduto = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btnContasPagar = new javax.swing.JButton();
        btnContasReceber = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroCliente = new javax.swing.JMenuItem();
        menuCadastroFornecedor = new javax.swing.JMenuItem();
        menuCadastroContaBancaria = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuCadastroUnidade = new javax.swing.JMenuItem();
        menuCadastroProduto = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCadastroDepartamento = new javax.swing.JMenuItem();
        menuCadastroFuncionario = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuCadastroCartao = new javax.swing.JMenuItem();
        menuCadastroPlanoConta = new javax.swing.JMenuItem();
        menuCadastroTipoPgtoRecebimento = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        menuMovimento = new javax.swing.JMenu();
        menuContasPagar = new javax.swing.JMenuItem();
        menuContasReceber = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenuItem();
        menuControleEstoque = new javax.swing.JMenu();
        menuEntradaNF = new javax.swing.JMenuItem();
        menuAtualizacaoPreco = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        menuRequisicao = new javax.swing.JMenuItem();
        menuCotacao = new javax.swing.JMenuItem();
        menuConfirmacaoCotacao = new javax.swing.JMenuItem();
        menuPedido = new javax.swing.JMenuItem();
        menuTesourariaBanco = new javax.swing.JMenu();
        menuEmissaoCheques = new javax.swing.JMenuItem();
        menuConciliacaoCheques = new javax.swing.JMenuItem();
        menuMovimentoBanco = new javax.swing.JMenuItem();
        menuUltilitarios = new javax.swing.JMenu();
        menuCalculadora = new javax.swing.JMenuItem();
        menuCalendario = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuSeguranca = new javax.swing.JMenu();
        menuSenha = new javax.swing.JMenuItem();
        menuNivelAcesso = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisCom - Sistema Comercial");

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(102, 204, 255));
        jToolBar1.setRollover(true);

        btnCadastroCliente.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/cadastro_cliente2.png")); // NOI18N
        btnCadastroCliente.setToolTipText("Cadastro de Clientes");
        btnCadastroCliente.setFocusable(false);
        btnCadastroCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCadastroCliente);

        btnCadastroFornecedor.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/fornecedor2.png")); // NOI18N
        btnCadastroFornecedor.setToolTipText("Cadastro de Fornecedores");
        btnCadastroFornecedor.setFocusable(false);
        btnCadastroFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroFornecedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFornecedorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCadastroFornecedor);

        btnCadastroProduto.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/cadastro_produto.png")); // NOI18N
        btnCadastroProduto.setToolTipText("Cadatro de Produtos");
        btnCadastroProduto.setFocusable(false);
        btnCadastroProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastroProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCadastroProduto);
        jToolBar1.add(jSeparator7);

        btnContasPagar.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/contas_pagar2.png")); // NOI18N
        btnContasPagar.setToolTipText("Contas a Pagar");
        btnContasPagar.setFocusable(false);
        btnContasPagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContasPagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnContasPagar);

        btnContasReceber.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/contas_receber2.png")); // NOI18N
        btnContasReceber.setToolTipText("Contas a Receber");
        btnContasReceber.setFocusable(false);
        btnContasReceber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContasReceber.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnContasReceber);
        jToolBar1.add(jSeparator8);

        btnSair.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/sair2.png")); // NOI18N
        btnSair.setToolTipText("Sair do SisCom");
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSair);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/aperto_maos.png")); // NOI18N
        jLabel1.setToolTipText("SisCom - Sistema Comercial");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        menuCadastro.setLabel("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        menuCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroCliente.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/cadastro_cliente.png")); // NOI18N
        menuCadastroCliente.setMnemonic('C');
        menuCadastroCliente.setText("Clientes");
        menuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroCliente);

        menuCadastroFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroFornecedor.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/fornecedor.png")); // NOI18N
        menuCadastroFornecedor.setMnemonic('F');
        menuCadastroFornecedor.setText("Fornecedores");
        menuCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroFornecedorActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroFornecedor);

        menuCadastroContaBancaria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroContaBancaria.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/banco.png")); // NOI18N
        menuCadastroContaBancaria.setMnemonic('B');
        menuCadastroContaBancaria.setText("Contas Bancaria");
        menuCadastroContaBancaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroContaBancariaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroContaBancaria);
        menuCadastro.add(jSeparator1);

        menuCadastroUnidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroUnidade.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/unidade.png")); // NOI18N
        menuCadastroUnidade.setMnemonic('U');
        menuCadastroUnidade.setText("Unidades");
        menuCadastro.add(menuCadastroUnidade);

        menuCadastroProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroProduto.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/produto.png")); // NOI18N
        menuCadastroProduto.setMnemonic('o');
        menuCadastroProduto.setText("Produtos");
        menuCadastro.add(menuCadastroProduto);
        menuCadastro.add(jSeparator2);

        menuCadastroDepartamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroDepartamento.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/departamento.png")); // NOI18N
        menuCadastroDepartamento.setMnemonic('D');
        menuCadastroDepartamento.setText("Departamentos");
        menuCadastro.add(menuCadastroDepartamento);

        menuCadastroFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroFuncionario.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/funcionario.png")); // NOI18N
        menuCadastroFuncionario.setMnemonic('i');
        menuCadastroFuncionario.setText("Funcionarios");
        menuCadastro.add(menuCadastroFuncionario);
        menuCadastro.add(jSeparator3);

        menuCadastroCartao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroCartao.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/cartao.png")); // NOI18N
        menuCadastroCartao.setMnemonic('a');
        menuCadastroCartao.setText("Cartões");
        menuCadastroCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroCartaoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroCartao);

        menuCadastroPlanoConta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroPlanoConta.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/plano_conta.png")); // NOI18N
        menuCadastroPlanoConta.setMnemonic('l');
        menuCadastroPlanoConta.setText("Planos de Conta");
        menuCadastroPlanoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPlanoContaActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroPlanoConta);

        menuCadastroTipoPgtoRecebimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroTipoPgtoRecebimento.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/tipo_pgto_recebimento.png")); // NOI18N
        menuCadastroTipoPgtoRecebimento.setMnemonic('g');
        menuCadastroTipoPgtoRecebimento.setText("Tipos de Pagamento / Recebimento");
        menuCadastroTipoPgtoRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroTipoPgtoRecebimentoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroTipoPgtoRecebimento);
        menuCadastro.add(jSeparator4);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuSair.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/sair.png")); // NOI18N
        menuSair.setLabel("Sair");
        menuCadastro.add(menuSair);

        jMenuBar1.add(menuCadastro);

        menuMovimento.setLabel("Movimento");

        menuContasPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuContasPagar.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/contas_pagar.png")); // NOI18N
        menuContasPagar.setMnemonic('P');
        menuContasPagar.setLabel("Contas a Pagar");
        menuMovimento.add(menuContasPagar);

        menuContasReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuContasReceber.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/contas_receber.png")); // NOI18N
        menuContasReceber.setMnemonic('R');
        menuContasReceber.setLabel("Contas a Receber");
        menuMovimento.add(menuContasReceber);

        menuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        menuVendas.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/venda.png")); // NOI18N
        menuVendas.setMnemonic('V');
        menuVendas.setLabel("Vendas");
        menuMovimento.add(menuVendas);

        menuControleEstoque.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/controle_estoque.png")); // NOI18N
        menuControleEstoque.setLabel("Controle de Estoque");

        menuEntradaNF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuEntradaNF.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/nota_fiscal.png")); // NOI18N
        menuEntradaNF.setMnemonic('N');
        menuEntradaNF.setLabel("Entrada de NF");
        menuControleEstoque.add(menuEntradaNF);

        menuAtualizacaoPreco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        menuAtualizacaoPreco.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/atualizacao_preco.png")); // NOI18N
        menuAtualizacaoPreco.setMnemonic('z');
        menuAtualizacaoPreco.setLabel("Atualização de Preços");
        menuControleEstoque.add(menuAtualizacaoPreco);

        menuMovimento.add(menuControleEstoque);

        menuCompras.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/compra.png")); // NOI18N
        menuCompras.setLabel("Compras");

        menuRequisicao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuRequisicao.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/requisicao.png")); // NOI18N
        menuRequisicao.setMnemonic('s');
        menuRequisicao.setLabel("Requisição");
        menuCompras.add(menuRequisicao);

        menuCotacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        menuCotacao.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/cotacao.png")); // NOI18N
        menuCotacao.setMnemonic('t');
        menuCotacao.setLabel("Cotação");
        menuCompras.add(menuCotacao);

        menuConfirmacaoCotacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menuConfirmacaoCotacao.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/confirma.png")); // NOI18N
        menuConfirmacaoCotacao.setLabel("Confirmar Cotação");
        menuCompras.add(menuConfirmacaoCotacao);

        menuPedido.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menuPedido.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/pedido.png")); // NOI18N
        menuPedido.setMnemonic('e');
        menuPedido.setLabel("Pedido");
        menuCompras.add(menuPedido);

        menuMovimento.add(menuCompras);

        menuTesourariaBanco.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/tesouraria_banco.png")); // NOI18N
        menuTesourariaBanco.setLabel("Tesouraria e Banco");

        menuEmissaoCheques.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        menuEmissaoCheques.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/cheque.png")); // NOI18N
        menuEmissaoCheques.setMnemonic('h');
        menuEmissaoCheques.setLabel("Emissão de Cheques");
        menuTesourariaBanco.add(menuEmissaoCheques);

        menuConciliacaoCheques.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuConciliacaoCheques.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/conciliacao_bancaria.png")); // NOI18N
        menuConciliacaoCheques.setMnemonic('q');
        menuConciliacaoCheques.setLabel("Conciliação de Cheques");
        menuTesourariaBanco.add(menuConciliacaoCheques);

        menuMovimentoBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuMovimentoBanco.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/banco.png")); // NOI18N
        menuMovimentoBanco.setMnemonic('M');
        menuMovimentoBanco.setLabel("Movimento de Banco");
        menuTesourariaBanco.add(menuMovimentoBanco);

        menuMovimento.add(menuTesourariaBanco);

        jMenuBar1.add(menuMovimento);

        menuUltilitarios.setLabel("Ultilitarios");

        menuCalculadora.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menuCalculadora.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/calculadora.png")); // NOI18N
        menuCalculadora.setLabel("Calculadora");
        menuUltilitarios.add(menuCalculadora);

        menuCalendario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuCalendario.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/calendario.png")); // NOI18N
        menuCalendario.setLabel("Calendario");
        menuUltilitarios.add(menuCalendario);
        menuUltilitarios.add(jSeparator5);

        menuSeguranca.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/seguranca.png")); // NOI18N
        menuSeguranca.setLabel("Sistema de Segurança");

        menuSenha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        menuSenha.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/senha.png")); // NOI18N
        menuSenha.setLabel("Trocar Senha Corrente");
        menuSeguranca.add(menuSenha);

        menuNivelAcesso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        menuNivelAcesso.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/nivel_acesso.png")); // NOI18N
        menuNivelAcesso.setLabel("Definir Nivel de Acesso");
        menuSeguranca.add(menuNivelAcesso);

        menuUltilitarios.add(menuSeguranca);

        jMenuBar1.add(menuUltilitarios);

        menuAjuda.setLabel("Ajuda");

        menuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuSobre.setIcon(new javax.swing.ImageIcon("/home/cesar/desenv/git/github/SisCom/Img/erp.png")); // NOI18N
        menuSobre.setLabel("Sobre o Sistema");
        menuAjuda.add(menuSobre);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(640, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroPlanoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPlanoContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastroPlanoContaActionPerformed

    private void menuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroClienteActionPerformed
       ClienteView.main(new String[]{"Cadastro de Clientes"});
    }//GEN-LAST:event_menuCadastroClienteActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void menuCadastroContaBancariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroContaBancariaActionPerformed
        ContaBancariaView.main(new String[]{"Cadastro das Contas Bancárias"});
    }//GEN-LAST:event_menuCadastroContaBancariaActionPerformed

    private void menuCadastroCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroCartaoActionPerformed
        CartaoCreditoView.main(new String[]{"Cadastro de Cartões"});
    }//GEN-LAST:event_menuCadastroCartaoActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void menuCadastroTipoPgtoRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroTipoPgtoRecebimentoActionPerformed
        TipoPgtoView.main(new String[]{"Cadastro de tipos de Pagamento / Recebimento"});
    }//GEN-LAST:event_menuCadastroTipoPgtoRecebimentoActionPerformed

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
        ClienteView.main(new String[]{"Cadastro de Clientes"});
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void menuCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroFornecedorActionPerformed
        FornecedorView.main(new String[]{"Cadastro de Fornecedores"});
    }//GEN-LAST:event_menuCadastroFornecedorActionPerformed

    private void btnCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFornecedorActionPerformed
         FornecedorView.main(new String[]{"Cadastro de Fornecedores"});
    }//GEN-LAST:event_btnCadastroFornecedorActionPerformed

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnCadastroFornecedor;
    private javax.swing.JButton btnCadastroProduto;
    private javax.swing.JButton btnContasPagar;
    private javax.swing.JButton btnContasReceber;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAtualizacaoPreco;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuCadastroCartao;
    private javax.swing.JMenuItem menuCadastroCliente;
    private javax.swing.JMenuItem menuCadastroContaBancaria;
    private javax.swing.JMenuItem menuCadastroDepartamento;
    private javax.swing.JMenuItem menuCadastroFornecedor;
    private javax.swing.JMenuItem menuCadastroFuncionario;
    private javax.swing.JMenuItem menuCadastroPlanoConta;
    private javax.swing.JMenuItem menuCadastroProduto;
    private javax.swing.JMenuItem menuCadastroTipoPgtoRecebimento;
    private javax.swing.JMenuItem menuCadastroUnidade;
    private javax.swing.JMenuItem menuCalculadora;
    private javax.swing.JMenuItem menuCalendario;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenuItem menuConciliacaoCheques;
    private javax.swing.JMenuItem menuConfirmacaoCotacao;
    private javax.swing.JMenuItem menuContasPagar;
    private javax.swing.JMenuItem menuContasReceber;
    private javax.swing.JMenu menuControleEstoque;
    private javax.swing.JMenuItem menuCotacao;
    private javax.swing.JMenuItem menuEmissaoCheques;
    private javax.swing.JMenuItem menuEntradaNF;
    private javax.swing.JMenu menuMovimento;
    private javax.swing.JMenuItem menuMovimentoBanco;
    private javax.swing.JMenuItem menuNivelAcesso;
    private javax.swing.JMenuItem menuPedido;
    private javax.swing.JMenuItem menuRequisicao;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSeguranca;
    private javax.swing.JMenuItem menuSenha;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenu menuTesourariaBanco;
    private javax.swing.JMenu menuUltilitarios;
    private javax.swing.JMenuItem menuVendas;
    // End of variables declaration//GEN-END:variables
}
