/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.siscom.view;

import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;

import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author cesar
 */
public class TipoPgtoView extends JPanel {

    public TipoPgtoView() {

        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("siscomPU").createEntityManager();
        query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM TipoPgto t");
        list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query.getResultList());
        pnlDadosTipoPgto = new javax.swing.JPanel();
        javax.swing.JTextField txtTipoPgtoDescricao = new javax.swing.JTextField();
        lblTipoPgtoDescricao = new javax.swing.JLabel();
        pnlListaTiposPgto = new javax.swing.JPanel();
        masterScrollPane = new javax.swing.JScrollPane();
        tblTiposPgto = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnNovoTipoPgto = new javax.swing.JButton();
        btnExcluirTipoPgto = new javax.swing.JButton();
        btnCancelarTipoPgto = new javax.swing.JButton();
        btnConfirmarTipoPgto = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        pnlDadosTipoPgto.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Tipo de Pgto/Recebimento"));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblTiposPgto, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.descricao}"), txtTipoPgtoDescricao, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblTiposPgto, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), txtTipoPgtoDescricao, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        lblTipoPgtoDescricao.setText("Tipo:");

        javax.swing.GroupLayout pnlDadosTipoPgtoLayout = new javax.swing.GroupLayout(pnlDadosTipoPgto);
        pnlDadosTipoPgto.setLayout(pnlDadosTipoPgtoLayout);
        pnlDadosTipoPgtoLayout.setHorizontalGroup(
            pnlDadosTipoPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosTipoPgtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoPgtoDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTipoPgtoDescricao)
                .addContainerGap())
        );
        pnlDadosTipoPgtoLayout.setVerticalGroup(
            pnlDadosTipoPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosTipoPgtoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDadosTipoPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoPgtoDescricao)
                    .addComponent(txtTipoPgtoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlListaTiposPgto.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Tipos de Pgto/Recebimento"));

        tblTiposPgto.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tblTiposPgto);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Tipo");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        masterScrollPane.setViewportView(tblTiposPgto);
        if (tblTiposPgto.getColumnModel().getColumnCount() > 0) {
            tblTiposPgto.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout pnlListaTiposPgtoLayout = new javax.swing.GroupLayout(pnlListaTiposPgto);
        pnlListaTiposPgto.setLayout(pnlListaTiposPgtoLayout);
        pnlListaTiposPgtoLayout.setHorizontalGroup(
            pnlListaTiposPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaTiposPgtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlListaTiposPgtoLayout.setVerticalGroup(
            pnlListaTiposPgtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaTiposPgtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNovoTipoPgto.setText("Novo");
        btnNovoTipoPgto.addActionListener(formListener);

        btnExcluirTipoPgto.setText("Excluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, tblTiposPgto, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnExcluirTipoPgto, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnExcluirTipoPgto.addActionListener(formListener);

        btnCancelarTipoPgto.setText("Cancelar Allterações");
        btnCancelarTipoPgto.addActionListener(formListener);

        btnConfirmarTipoPgto.setText("Confirmar Allterações");
        btnConfirmarTipoPgto.addActionListener(formListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoTipoPgto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirTipoPgto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarTipoPgto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarTipoPgto)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarTipoPgto, btnConfirmarTipoPgto, btnExcluirTipoPgto, btnNovoTipoPgto});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarTipoPgto)
                    .addComponent(btnCancelarTipoPgto)
                    .addComponent(btnExcluirTipoPgto)
                    .addComponent(btnNovoTipoPgto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDadosTipoPgto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlListaTiposPgto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlListaTiposPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlDadosTipoPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == btnNovoTipoPgto) {
                TipoPgtoView.this.btnNovoTipoPgtoActionPerformed(evt);
            }
            else if (evt.getSource() == btnExcluirTipoPgto) {
                TipoPgtoView.this.btnExcluirTipoPgtoActionPerformed(evt);
            }
            else if (evt.getSource() == btnCancelarTipoPgto) {
                TipoPgtoView.this.btnCancelarTipoPgtoActionPerformed(evt);
            }
            else if (evt.getSource() == btnConfirmarTipoPgto) {
                TipoPgtoView.this.btnConfirmarTipoPgtoActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void btnCancelarTipoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoPgtoActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_btnCancelarTipoPgtoActionPerformed

    private void btnExcluirTipoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTipoPgtoActionPerformed
        int[] selected = tblTiposPgto.getSelectedRows();
        List<br.com.siscom.bean.TipoPgto> toRemove = new ArrayList<>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            br.com.siscom.bean.TipoPgto t = list.get(tblTiposPgto.convertRowIndexToModel(selected[idx]));
            toRemove.add(t);
            entityManager.remove(t);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_btnExcluirTipoPgtoActionPerformed

    private void btnNovoTipoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoTipoPgtoActionPerformed
        br.com.siscom.bean.TipoPgto t = new br.com.siscom.bean.TipoPgto();
        entityManager.persist(t);
        list.add(t);
        int row = list.size() - 1;
        tblTiposPgto.setRowSelectionInterval(row, row);
        tblTiposPgto.scrollRectToVisible(tblTiposPgto.getCellRect(row, 0, true));
    }//GEN-LAST:event_btnNovoTipoPgtoActionPerformed

    private void btnConfirmarTipoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarTipoPgtoActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            entityManager.getTransaction().begin();
            List<br.com.siscom.bean.TipoPgto> merged = new ArrayList<>(list.size());
            for (br.com.siscom.bean.TipoPgto t : list) {
                merged.add(entityManager.merge(t));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_btnConfirmarTipoPgtoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTipoPgto;
    private javax.swing.JButton btnConfirmarTipoPgto;
    private javax.swing.JButton btnExcluirTipoPgto;
    private javax.swing.JButton btnNovoTipoPgto;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTipoPgtoDescricao;
    private java.util.List<br.com.siscom.bean.TipoPgto> list;
    private javax.swing.JScrollPane masterScrollPane;
    private javax.swing.JPanel pnlDadosTipoPgto;
    private javax.swing.JPanel pnlListaTiposPgto;
    private javax.persistence.Query query;
    private javax.swing.JTable tblTiposPgto;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    public static void main(final String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoPgtoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame();
                frame.setContentPane(new TipoPgtoView());
                //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.pack();
                frame.setVisible(true);
                if (args.length > 0) {
                    frame.setTitle(args[0]);
                }

            }
        });
    }

}
