--Tabela de Juros dos Cartões de Credito
--http://www.anucc.org.br/servicos/index/25

insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('American Express Card',                   'PayFlex 5,5%',   100, 11.9,  2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('American Express Credit',                 '5,95% a 10,95%', 20,  11.95, 2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('American Express Platinum',               'PayFlex 5,5%',   20,  11.9,  2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bandeirantes MasterCard',                 '10,9%',          20,  10.8,  2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bandeirantes Texaco Domestico Visa',      '12,94%',         20,  10,    2,    'Minimo', 1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bandeirantes Texaco Internacional Visa',  '11,95%',         20,  10,    2,    'Minimo', 1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bandeirantes Texaco Gold Visa',           '8,95%',          20,  10,    2,    'Minimo', 1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Banerj Visa',                             '11,7%',          20,  10.38, 2,    'Minimo', 5);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Baneb Visa',                              '10%',            20,  10,    2,    'Total',  7);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Banespa Visa Classic',                    '10,45%',         20,  10.42, 2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Banespa Visa Gold',                       '5,4%',           20,  10.42, 2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Banestes Visa Internacional',             '9,5%',           25,  7.5,   2,    'Minimo', 5);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Banrisul Visa',                           '9,95%',          25,  9.95,  2,    'Minimo', 5);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Boston Visa',                             '13%',            20,  9,     2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Boston Visa Platrinum',                   '13%',            20,  9,     2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bradesco Visa/MasterCard Domestico',      '11,25%',         10,  10.5,  null, null,     null);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bradesco Visa /MasterCard Internacional', '11,2%',          14,  10.5,  null, null,     null);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bradesco Visa/MasterCard Gold',           '10,6%',          10,  10.5,  null, null,     null);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bradesco Diners',                         '13%',            10,  10.8,  2,    'Total',  1);
insert into cartao_credito(empresa, juros_rotativo, pagto_minimo, juros_parcelado, multa, multa_sem_minimo_total, multa_cobrada_dia) values('Bradesco Platinum',                       '5,5%',           10,  8.5,   null, null,     null);