--DCL – Data Control Language ( DCL ) declarações. Alguns exemplos:
--GRANT – atribui privilégios de acesso do usuário a objetos do banco de dados
--REVOKE – remove os privilégios de acesso aos objetos obtidos com o comando GRANT