--TCL – Transaction Control Language – (Controle de Transações) são usados ​​para gerenciar as mudanças feitas por instruções DML . Ele permite que as declarações a serem agrupadas em transações lógicas .
--COMMIT – salvar o trabalho feito
--SAVEPOINT – identificar um ponto em uma transação para que mais tarde você pode efetuar um ROLLBACK
--ROLLBACK – restaurar banco de dados ao original desde o último COMMIT